/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Iniciar sesión */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registrar usuario */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cerrar sesión */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear perfil de usuario */
        post: operations["UserController_createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/allActive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener todos los usuarios activos */
        get: operations["UserController_getActiveUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener usuario actual */
        get: operations["UserController_getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/author/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener información del usuario como autor */
        get: operations["UserController_getInfoAuthor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener usuario por UID */
        get: operations["UserController_getUser"];
        /** Actualizar usuario por UID (admin) */
        put: operations["UserController_updateUser"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Actualizar usuario actual */
        put: operations["UserController_updateCurrentUser"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Actualizar foto del usuario actual */
        patch: operations["UserController_updateCurrentUserPhoto"];
        trace?: never;
    };
    "/user/{uid}/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Actualizar foto de usuario por UID (admin) */
        patch: operations["UserController_updateUserPhoto"];
        trace?: never;
    };
    "/user/desactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Desactivar usuario actual */
        patch: operations["UserController_deactivateCurrentUser"];
        trace?: never;
    };
    "/user/{uid}/desactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Desactivar usuario por UID (admin) */
        patch: operations["UserController_deactivateUser"];
        trace?: never;
    };
    "/user/{uid}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reactivar usuario (admin) */
        patch: operations["UserController_reactivateUser"];
        trace?: never;
    };
    "/photos/get/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener foto por UID */
        get: operations["PhotosController_getPhoto"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear foto */
        post: operations["PhotosController_createPhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/edit/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Actualizar foto */
        put: operations["PhotosController_updatePhoto"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/styles/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener todos los estilos */
        get: operations["StylesController_getAllStyles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/styles/all/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener estilos por grupo */
        get: operations["StylesController_getAllByGroup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/styles/get/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener estilo por UID */
        get: operations["StylesController_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/styles/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear estilo */
        post: operations["StylesController_createStyle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/styles/update/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Actualizar estilo */
        put: operations["StylesController_updateStyle"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/styles/delete/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Eliminar estilo */
        delete: operations["StylesController_deleteStyle"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear grupo */
        post: operations["GroupController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener todos los grupos */
        get: operations["GroupController_getAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/get/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener grupo por UID */
        get: operations["GroupController_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/update/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Actualizar grupo */
        put: operations["GroupController_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/delete/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Eliminar grupo */
        delete: operations["GroupController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/student/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Agregar estudiante a grupo(s) */
        post: operations["GroupController_addStudent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/student/get/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener estudiantes de un grupo */
        get: operations["GroupController_getAllStudents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/student/delete/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Eliminar un estudiante del grupo */
        delete: operations["GroupController_deleteStudent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/student/deleteAll/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Eliminar todos los estudiantes del grupo */
        delete: operations["GroupController_deleteAllStudents"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/student/update/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Actualizar lista de estudiantes del grupo */
        put: operations["GroupController_updateStudents"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear una obra */
        post: operations["ProductController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/getAll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener todos los productos paginadas */
        get: operations["ProductController_getAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/getGalleryHome": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener obras para galería home */
        get: operations["ProductController_getGalleryHome"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/getGroup/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener obras por grupo */
        get: operations["ProductController_getAllByGroup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/getAuthor/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener obras por autor */
        get: operations["ProductController_getAllByAuthor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/get/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener obra por ID */
        get: operations["ProductController_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/approveMany": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Aprobar varias obras seleccionadas a la vez */
        put: operations["ProductController_approveManyProducts"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/status/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Aprobar o negar una obra individual */
        patch: operations["ProductController_updateProductStatus"];
        trace?: never;
    };
    "/products/update/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Actualizar una obra */
        put: operations["ProductController_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear un evento */
        post: operations["EventController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/getAll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener todos los eventos paginados (admin) */
        get: operations["EventController_getAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener eventos próximos aprobados (público) */
        get: operations["EventController_getUpcoming"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/past": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener eventos pasados completados (público) */
        get: operations["EventController_getPast"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener eventos próximos para la página de inicio (público) */
        get: operations["EventController_getHome"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/getByGroup/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener eventos de un grupo específico (público) */
        get: operations["EventController_getByGroup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/available-products/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener obras APPROVED del grupo disponibles para un evento */
        get: operations["EventController_getAvailableProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/invitations/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ver invitaciones pendientes del profesor autenticado */
        get: operations["EventController_getPendingInvitations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/get/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener detalle completo de un evento (público) */
        get: operations["EventController_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/update/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Editar info general del evento (vuelve a PENDING) */
        put: operations["EventController_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/status/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cambiar el status de un evento (admin) */
        patch: operations["EventController_updateStatus"];
        trace?: never;
    };
    "/events/deactivate/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Desactivar un evento (soft delete, admin) */
        patch: operations["EventController_deactivate"];
        trace?: never;
    };
    "/events/{uid}/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Actualizar obras del grupo en el evento (vuelve a PENDING) */
        put: operations["EventController_updateProducts"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{uid}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Agregar foto al evento (HERO/PROMO: coordinador/admin · MEMORY: participante) */
        post: operations["EventController_addPhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{uid}/photos/{photoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Eliminar una foto del evento */
        delete: operations["EventController_removePhoto"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{uid}/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enviar invitación a un grupo (coordinador/admin) */
        post: operations["EventController_sendInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/invitations/{uid}/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Aceptar o rechazar una invitación (profesor invitado) */
        patch: operations["EventController_respondInvitation"];
        trace?: never;
    };
    "/events/{uid}/invite/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revocar invitación de un grupo (coordinador/admin) */
        delete: operations["EventController_revokeInvitation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateCredentialDto: {
            /** @example usuario@correo.com */
            mail: string;
            /** @example password123 */
            password: string;
        };
        PhotoDto: {
            /** @example /9j/4AAQSkZJRgAB... */
            base64: string;
            /** @example foto.jpeg */
            name: string;
            /** @example users */
            folder: string;
        };
        CreateUserDto: {
            /** @example Juan */
            name: string;
            /** @example Pérez */
            lastName: string;
            /** @example juanperez */
            username: string;
            /** @example Estudiante de artes */
            description?: string;
            /** @example M */
            gender: string;
            /** @example 123456789 */
            idCard: string;
            /** @example Artes Plásticas */
            degree: string;
            /** @example 5 */
            semester: string;
            /** @example 3001234567 */
            telNumber: string;
            /** @example false */
            isProfesor?: boolean;
            /** @example uuid-del-tipo */
            userTypeId: string;
            photo?: components["schemas"]["PhotoDto"];
        };
        UpdateUserDto: {
            /** @example Juan */
            name?: string;
            /** @example Pérez */
            lastName?: string;
            /** @example juanperez */
            username?: string;
            description?: string;
            /** @example M */
            gender?: string;
            degree?: string;
            semester?: string;
            telNumber?: string;
            isProfesor?: boolean;
            userTypeId?: string;
        };
        UpdateUserPhotoDto: {
            /** @example /9j/4AAQSkZJRgAB... */
            base64: string;
            /** @example foto.jpeg */
            name: string;
            /** @example users */
            folder: string;
        };
        CreatePhotoDto: {
            /** @example /9j/4AAQSkZJRgAB... */
            base64: string;
            /** @example obra.jpeg */
            name: string;
            /** @example products */
            folder: string;
        };
        UpdatePhotoDto: {
            /** @example /9j/4AAQSkZJRgAB... */
            base64: string;
        };
        CreateStyleDto: {
            /** @example Expresionismo */
            name: string;
            /** @example Estilo caracterizado por la distorsión emocional */
            description: string;
            /** @example uuid-del-grupo */
            groupId: string;
        };
        UpdateStyleDto: {
            /** @example Surrealismo */
            name?: string;
            /** @example Nueva descripción */
            description?: string;
        };
        CreateGroupDto: {
            /** @example Grupo A 2025 */
            name: string;
            /** @example uuid-del-profesor */
            profesorId: string;
            /**
             * @description IDs de los alumnos a agregar al grupo (opcional)
             * @example [
             *       "uuid-alumno-1",
             *       "uuid-alumno-2"
             *     ]
             */
            users?: string[];
        };
        UpdateGroupDto: {
            /** @example Grupo B 2025 */
            name?: string;
            /** @example uuid-del-profesor */
            profesorId?: string;
        };
        AddStudentDto: {
            /** @example uuid-del-usuario */
            userId?: string;
            /**
             * @example [
             *       "uuid-grupo-1",
             *       "uuid-grupo-2"
             *     ]
             */
            groupIds: string[];
        };
        DeleteStudentDto: {
            /** @example uuid-del-usuario */
            userId: string;
        };
        UpdateStudentsDto: {
            /**
             * @example [
             *       "uuid-alumno-1",
             *       "uuid-alumno-2"
             *     ]
             */
            users: string[];
        };
        ProductAuthorDto: {
            /** @example aa35ee0c-f81a-4739-aa4c-af4cdfa820d3 */
            userId: string;
            /** @example true */
            isAuthor: boolean;
        };
        ProductImageDto: {
            /** @example /9j/4AAQSkZJRgAB... */
            base64: string;
            /** @example obra.jpeg */
            name: string;
            /** @example products */
            folder: string;
            /** @example true */
            isMain?: boolean;
        };
        CreateProductDto: {
            /** @example Mi hermosa novia */
            name: string;
            /** @example Obra hecha en acuarela */
            description: string;
            /** @example 99999 */
            price?: number;
            /** @example 2025-07-29 */
            madeAt: string;
            /** @example b4fa2024-0da5-49a9-bc29-2417515e118c */
            groupId: string;
            /** @example false */
            isSold?: boolean;
            authors: components["schemas"]["ProductAuthorDto"][];
            /**
             * @example [
             *       "Expresionismo"
             *     ]
             */
            styles?: string[];
            images?: components["schemas"]["ProductImageDto"][];
        };
        ApproveManyDto: {
            /**
             * @example [
             *       "aa35ee0c-f81a-4739-aa4c-af4cdfa820d3",
             *       "b4fa2024-0da5-49a9-bc29-2417515e118c"
             *     ]
             */
            productIds: string[];
        };
        UpdateProductStatusDto: {
            /**
             * @example APPROVED
             * @enum {string}
             */
            status: "APPROVED" | "REJECTED" | "PENDING";
            /** @example La resolución de la imagen es muy baja. */
            feedback?: string;
        };
        UpdateProductImageDto: {
            /** @example uuid-foto */
            uid?: string;
            /** @example /9j/4AAQSkZJRgAB... */
            base64?: string;
            /** @example foto.jpg */
            name?: string;
            /** @example products */
            folder?: string;
            /** @example true */
            isMain: boolean;
            /** @example false */
            isExisting: boolean;
        };
        UpdateProductDto: {
            /** @example Nuevo nombre */
            name?: string;
            /** @example Nueva descripción */
            description?: string;
            /** @example 50000 */
            price?: number;
            /** @example 2025-07-29 */
            madeAt?: string;
            /** @example false */
            isSold?: boolean;
            styles?: string[];
            authors?: components["schemas"]["ProductAuthorDto"][];
            images?: components["schemas"]["UpdateProductImageDto"][];
        };
        EventPhotoDto: {
            /** @example /9j/4AAQSkZJRgAB... */
            base64: string;
            /** @example portada.jpeg */
            name: string;
            /** @example events */
            folder: string;
            /**
             * @example PROMO
             * @enum {string}
             */
            photoType: "HERO" | "PROMO" | "MEMORY";
        };
        CreateEventDto: {
            /** @example Exposición Semestral 2025 */
            name: string;
            /** @example Exhibición de obras del semestre realizada en el auditorio central. */
            description: string;
            /**
             * @example EXHIBITION
             * @enum {string}
             */
            eventType: "EXHIBITION" | "WORKSHOP" | "PERFORMANCE" | "CONFERENCE" | "OTHER";
            /** @example 2025-10-15T14:00:00.000Z */
            startDate: string;
            /** @example 2025-10-15T18:00:00.000Z */
            endDate?: string;
            /** @example https://maps.google.com/?q=... */
            locationUrl?: string;
            /** @example false */
            isVirtual: boolean;
            /** @example https://meet.google.com/abc-xyz */
            streamingUrl?: string;
            /** @example aa35ee0c-f81a-4739-aa4c-af4cdfa820d3 */
            createdById: string;
            /**
             * @example [
             *       "uuid-grupo-1"
             *     ]
             */
            groupIds: string[];
            /**
             * @example [
             *       "uuid-obra-1"
             *     ]
             */
            productIds?: string[];
            coverPhoto?: components["schemas"]["EventPhotoDto"];
        };
        UpdateEventDto: {
            /** @example Nuevo nombre del evento */
            name?: string;
            /** @example Nueva descripción. */
            description?: string;
            /** @enum {string} */
            eventType?: "EXHIBITION" | "WORKSHOP" | "PERFORMANCE" | "CONFERENCE" | "OTHER";
            /** @example 2025-11-01T14:00:00.000Z */
            startDate?: string;
            /** @example 2025-11-01T18:00:00.000Z */
            endDate?: string;
            /** @example https://maps.google.com/?q=... */
            locationUrl?: string;
            /** @example false */
            isVirtual?: boolean;
            /** @example https://meet.google.com/abc-xyz */
            streamingUrl?: string;
        };
        UpdateEventStatusDto: {
            /**
             * @example APPROVED
             * @enum {string}
             */
            status: "PENDING" | "APPROVED" | "REJECTED" | "CANCELLED" | "COMPLETED";
            /** @example La fecha del evento coincide con otro evento aprobado. */
            feedback?: string;
        };
        UpdateEventProductsDto: {
            /**
             * @example [
             *       "uuid-obra-1",
             *       "uuid-obra-2"
             *     ]
             */
            productIds: string[];
            /** @example uuid-grupo */
            groupId: string;
        };
        SendInvitationDto: {
            /** @example uuid-grupo-invitado */
            groupId: string;
        };
        RespondInvitationDto: {
            /**
             * @example ACCEPTED
             * @enum {string}
             */
            status: "ACCEPTED" | "REJECTED";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCredentialDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCredentialDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_getActiveUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_getInfoAuthor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_updateCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_updateCurrentUserPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserPhotoDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_updateUserPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserPhotoDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_deactivateCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_deactivateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_reactivateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PhotosController_getPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PhotosController_createPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePhotoDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PhotosController_updatePhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePhotoDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StylesController_getAllStyles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StylesController_getAllByGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StylesController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StylesController_createStyle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStyleDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StylesController_updateStyle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStyleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StylesController_deleteStyle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GroupController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GroupController_getAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GroupController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GroupController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGroupDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GroupController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GroupController_addStudent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddStudentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GroupController_getAllStudents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GroupController_deleteStudent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteStudentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GroupController_deleteAllStudents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GroupController_updateStudents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStudentsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_getAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                styleId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_getGalleryHome: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                styleId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_getAllByGroup: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                styleId?: string;
            };
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_getAllByAuthor: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                styleId?: string;
            };
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_approveManyProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveManyDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_updateProductStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_getAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                status?: "PENDING" | "APPROVED" | "REJECTED" | "CANCELLED" | "COMPLETED";
                eventType?: "EXHIBITION" | "WORKSHOP" | "PERFORMANCE" | "CONFERENCE" | "OTHER";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_getUpcoming: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                status?: "PENDING" | "APPROVED" | "REJECTED" | "CANCELLED" | "COMPLETED";
                eventType?: "EXHIBITION" | "WORKSHOP" | "PERFORMANCE" | "CONFERENCE" | "OTHER";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_getPast: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                status?: "PENDING" | "APPROVED" | "REJECTED" | "CANCELLED" | "COMPLETED";
                eventType?: "EXHIBITION" | "WORKSHOP" | "PERFORMANCE" | "CONFERENCE" | "OTHER";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_getHome: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                status?: "PENDING" | "APPROVED" | "REJECTED" | "CANCELLED" | "COMPLETED";
                eventType?: "EXHIBITION" | "WORKSHOP" | "PERFORMANCE" | "CONFERENCE" | "OTHER";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_getByGroup: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                status?: "PENDING" | "APPROVED" | "REJECTED" | "CANCELLED" | "COMPLETED";
                eventType?: "EXHIBITION" | "WORKSHOP" | "PERFORMANCE" | "CONFERENCE" | "OTHER";
            };
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_getAvailableProducts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_getPendingInvitations: {
        parameters: {
            query: {
                profesorId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_updateProducts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventProductsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_addPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventPhotoDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_removePhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
                photoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_sendInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendInvitationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_respondInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RespondInvitationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_revokeInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
